project:
  type: book
  output-dir: docs
  
book:
  title: "GEOG0114 Principles of Spatial Analysis"
  author: "Justin van Dijk"
  date: "9/19/2023"
  chapters:
  
    - index.qmd
    - 01-geodemographics.qmd
    - 02-network.qmd

format:
  html:
    theme: 
      minty
    css:
      custom.css
    code-overflow: wrap
    code-tools: 
      source: https://github.com/jtvandijk/GEOG0114Q
      toggle: false
      caption: "R"
    code-block-border-left: "#99d8c9"
    code-block-bg: "#f0f0f0"
# pdf:
#    documentclass: scrreprt
#    prefer-html: true

title-block-banner: false
editor: source

