# project
project:
  type: book
  output-dir: docs

# front matter
book:
  title: "GEOG0114 Principles of Spatial Analysis"
  author: "Justin van Dijk"
  date: "9/22/2023"
  chapters:
  
    - index.qmd
    - 01-geodemographics.qmd
    - 02-network.qmd
    
  downloads: [pdf]

# output
format:
  html:
    theme: 
      flatly
    css:
      custom.css
    code-overflow: scroll
    code-tools: 
      source: https://github.com/jtvandijk/GEOG0114Q
      toggle: false
      caption: none
    code-block-bg: "#f0f0f0"
    callout-appearance: simple
  pdf: 
    pdf-engine: xelatex
    code-overflow: wrap
      
# misc
title-block-banner: false
editor: source

